name: Build Re:WearBili

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   build-release:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone wearbili
      run: cd .. && sudo rm -rf Re-WearBili && git clone https://github.com/dudu-Dev0/Re-WearBili.git Re-WearBili
    - name: ls
      run: ls -l /home/runner/work/Re-WearBili/Re-WearBili
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clone Submodules
      run: git submodule update --init --recursive
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleRelease
    - uses: ilharp/sign-android-release@nightly # Or use @nightly
      name: Sign app APK
      id: sign_app
      with:
        releaseDir: app/build/outputs/apk/release
        signingKey: ${{ secrets.KEY_STORE }}
        keyAlias: ${{ secrets.ALIAS_NAME }}
        keyStorePassword: ${{ secrets.KEY_PASSWORD }}
        keyPassword: ${{ secrets.ALIAS_PASSWORD }}
        buildToolsVersion: 30.0.3
    - name: Upload APK(release)
      uses: actions/upload-artifact@v4
      with:
          name: app-release
          path: ${{steps.sign_app.outputs.signedFile}}
